### ISSUE TITLE
any chance for this library to be updated?

### ISSUE THREAD

**Issue by zen85** [mkkellogg/TrailRendererJS#11]
i was on the lookout for something exactly like this but for other reasons i need to be up to date on three.js and unfortunatly this beautiful library is not compatible anymore and i could not find anything even remotely resembling this.

Is there any chance?

**Comment by nitrogem35** [comment]
I went ahead and fixed it (mostly issues with three.js features being renamed in newer versions), here you go if you still need it:

[TrailRenderer.txt](https://github.com/mkkellogg/TrailRendererJS/files/10407847/TrailRenderer.txt)

**Comment by mkkellogg** [comment]
@nitrogem35 Sorry for the very late response, I'm way too busy with work these days -- I see you've already made your own fork, but if by chance you'd still like to make a PR with your updates I'd be happy to incorporate them.

**Comment by mkkellogg** [comment]
I went ahead and updated the code to work with three.js version 151. Thanks for bringing this issue to my attention!
